// Generated by gencpp from file teste2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TESTE2_MESSAGE_ADDTWOINTS_H
#define TESTE2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <teste2/AddTwoIntsRequest.h>
#include <teste2/AddTwoIntsResponse.h>


namespace teste2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace teste2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::teste2::AddTwoInts > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::teste2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::teste2::AddTwoInts > {
  static const char* value()
  {
    return "teste2/AddTwoInts";
  }

  static const char* value(const ::teste2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::teste2::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::teste2::AddTwoInts >
template<>
struct MD5Sum< ::teste2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::teste2::AddTwoInts >::value();
  }
  static const char* value(const ::teste2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::teste2::AddTwoIntsRequest> should match
// service_traits::DataType< ::teste2::AddTwoInts >
template<>
struct DataType< ::teste2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::teste2::AddTwoInts >::value();
  }
  static const char* value(const ::teste2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::teste2::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::teste2::AddTwoInts >
template<>
struct MD5Sum< ::teste2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::teste2::AddTwoInts >::value();
  }
  static const char* value(const ::teste2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::teste2::AddTwoIntsResponse> should match
// service_traits::DataType< ::teste2::AddTwoInts >
template<>
struct DataType< ::teste2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::teste2::AddTwoInts >::value();
  }
  static const char* value(const ::teste2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTE2_MESSAGE_ADDTWOINTS_H
